import React from "react"

const TermsPage1 = () => {
  return (
    <div className="">
      <div className="">
        <div className="grid sm:grid-cols-2 gap-4 ">
          <div className="md:m-5 sm:py-20 overflow-hidden order-2 md:order-2">
            <span className="md:text-4xl text-3xl font-semibol font-serif justify-center flex ">
              Terms &amp; Conditions
            </span>
            <p className=" font-serif text-stone-600 p-3 m-3 text-justify ">
              Windsor Trade, The Company is engaged in the business of,
              multilevel marketing by offering a single unified user-id to the
              members for accepting menbership in exchenge of WINDSOR crypto
              coins.
            </p>
          </div>
          <div className="order-1 md:order-2 py-4 md:py-0  md:pt-0 pt-1 flex justify-center ">
            <img
              className="md:w-80 md:h-80 w-40 h-40"
              src="https://windsorcryptocoin.com/img/bg-img/bg-2.png"
            />
          </div>
        </div>
        <div className="text-lg font-serif p-4 ">
          1. REPRESENTATIONS, WARRANTIES AND COVENANTS
        </div>
        <div className="mr-6 ">
          <div className="text-sm mt-3 text-stone-700 text-justify pl-1">
            1.1 You hereby represent, warrant and covenant with windsor trade
            that:{" "}
          </div>
          <div className="p-4">
            <div className="text-sm mt-3 text-stone-700 text-justify">
              1.1.1. all information submitted by you to windsor trade is and
              shall during the tenure of the engagement be maintained as true,
              correct and accurate in all respects;
            </div>

            <div className="text-sm mt-3 text-stone-700 text-justify">
              1.1.2. you are not barred or otherwise prohibited from accessing
              or using windsor trade Services in any manner;
            </div>

            <div className="text-sm mt-3 text-stone-700 text-justify">
              1.1.3. you are and shall, during the tenure of this engagement,
              remain at all times the legal and beneficial and keep all details
              thereof up to date;
            </div>
            <div className="text-sm mt-3 text-stone-700 text-justify">
              1.1.4. all goods and/or services provided by you to a Customer
              shall be lawfully sold/provided and that you shall not sell/
              provide products that are or may be perceived as illegal,
              offensive or prohibited and such other Services in Annexure ;
            </div>
            <div className="text-sm mt-3 text-stone-700 text-justify">
              1.1.5. you shall not impersonate any person or entity, falsely
              claim or otherwise misrepresent an affiliation with any person or
              entity, or access the accounts of others without permission, forge
              another person’s digital signatures or perform any other
              fraudulent activity;
            </div>
            <div className="text-sm mt-3 text-stone-700 text-justify">
              1.1.6. you shall promote windsor trade at your place of business
              and website;
            </div>
            <div className="text-sm mt-3 text-stone-700 text-justify">
              1.1.7. you shall promptly provide all information and assistance
              as may be required by windsor trade from time to time in dealing
              with requests or queries of any governmental authority or
              judicial/quasi-judicial authorities;
            </div>
            <div className="text-sm mt-3 text-stone-700 text-justify">
              1.2 You agree to provide KYC and similar relevant details &
              documents to windsor trade, in electronic and physical form, as
              may be required by windsor trade. Also, you hereby authorise
              windsor trade to use your KYC and details for all such services
              that windsor trade may offer, by itself or through third parties,
              from time to time.
            </div>
            <div className="text-sm mt-3 text-stone-700 text-justify">
              1.3 You authorise windsor trade to read and access messages on the
              device utilising the windsor trade Services for retrieval and use
              for the enhancement of windsor s services.
            </div>
            <div className="text-sm mt-3 text-stone-700 text-justify">
              1.4 You understand that the QR Code which shall be generated by
              windsor trade for it is unique and specific to you and that you
              shall at all times maintain the secrecy of this QR Code.
              Specifically, you agree and acknowledge that windsor trade shall
              not be liable in any manner whatsoever for any negligence or
              misuse of the QR Code by you or your agents, employees,
              representatives or Customers.
            </div>
            <div className="text-sm mt-3 text-stone-700 text-justify">
              1.5 You agree and understand that at the time of registration with
              windsor trade, a username and password shall be generated which is
              enable you to access your unique and personal dashboard on windsor
              trade interface and view Transactions. You shall not share the
              username and password with other persons and acknowledge that such
              sharing shall cause irreparable harm to windsor trade and that you
              shall be liable to indemnify windsor trade for any loss or damage
              suffered as a result of any unauthorised use.
            </div>
            <div className="text-sm mt-3 text-stone-700 text-justify">
              1.1 windsor trade shall provide you details of Transactions
              through a personal dashboard on windsor trade interface and you
              shall determine if there are any errors or unauthorised
              Transactions, and intimate windsor trade in writing of the same.
            </div>
            <div className="text-sm mt-3 text-stone-700 text-justify">
              1.7 you shall deliver goods/services immediately to Customers upon
              receiving the confirmation of payment;
            </div>
            <div className="text-sm mt-3 text-stone-700 text-justify">
              1.8 you have appointed windsor trade as a collection agent for
              payments to be received by it;
            </div>
            <div className="text-sm mt-3 text-stone-700 text-justify">
              1.9 It is agreed that windsor trade shall be entitled to rely upon
              all electronic communications, orders or messages sent to windsor
              trade through the Processing Mechanism in processing the
              Transactions. windsor trade shall not be obligated to verify or
              make further inquiry into the identity of the sender, or integrity
              of any communications. windsor trade shall not be responsible for
              any losses sustained through the use of stolen or hacked devices
              or fraudulent electronic transactions.
            </div>
          </div>
        </div>
      </div>
      <div className="m-4 p-3 ">
        <div className="text-lg font-serif  ">
          2. CONFIDENTIALITY AND INTELLECTUAL PROPERTY
        </div>
        <div className="mr-6 ">
          <div className="text-sm mt-3 text-stone-700 text-justify">
            2.1 Each Party acknowledges that, pursuant to these Terms and
            Conditions, it may have access to certain confidential information
            of the other Party and accordingly, each receiving Party agrees not
            to disclose to any third party any confidential information of a
            disclosing Party.{" "}
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            2.2 You shall ensure that no person who has access to any windsor
            trade Services shall reverse engineer, decompile or disassemble any
            software shared/disclosed by windsor trade, or write or develop any
            derivative software or any other software program based thereon.
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            2.3 windsor trade shall exclusively retain all worldwide rights,
            title and interest in and to the windsor trade Services (including
            without limitation ownership of all intellectual property rights
            therein and to the Processing Mechanism enabled by windsor trade and
            software related thereto). You understand and agree that the
            customizations, if any, carried out for and on behalf of you shall
            be intellectual property rights of windsor trade and that you can
            only use such additional modifications/ amendments during the term
            of the engagement.
          </div>
        </div>
      </div>
      <div className="m-4 p-3 ">
        <div className="text-lg font-serif  ">3. INDEMNIFICATION</div>
        <div className="mr-6 ">
          <div className="text-sm mt-3 text-stone-700 text-justify">
            3.1 You hereby undertake and agree to indemnify and hold harmless
            windsor trade against all actions, proceedings, claims, penalties,
            demands and costs (including without limitation, legal costs of
            windsor trade), awards, damages, losses, liabilities and/or
            expenses, however arising out of or in connection with:{" "}
          </div>
          <div className="p-4">
            <div className="text-sm mt-3 text-stone-700 text-justify">
              3.1.1. any claim of or proceeding brought by a Customer in
              relation to product and/or service offered or sold by you; and
            </div>
            <div className="text-sm mt-3 text-stone-700 text-justify">
              3.1.2. any negligence by you or any of your agents, employees,
              licensees, contractors or Customers;
            </div>
            <div className="text-sm mt-3 text-stone-700 text-justify">
              3.1.3. a breach of any term or condition mentioned herein, by you
              or any inaccuracy of a representation or warranty given by you
              hereunder;
            </div>
            <div className="text-sm mt-3 text-stone-700 text-justify">
              3.1.4. a breach of applicable laws.
            </div>
          </div>
        </div>
      </div>
      <div className="m-4 p-3 ">
        <div className="text-lg font-serif  ">4. LIMITATION OF LIABILITY</div>
        <div className="mr-6 text-justify ">
          <div className="text-sm mt-3 text-stone-700 text-justify">
            4.1 Unless otherwise required by applicable law, all Transactions
            processed through windsor trade Services are non-refundable.windsor
            trade is not a party to and shall not be responsible for any
            disputes, chargebacks or reversals amongst you and a
            Customer.Notwithstanding anything contrary contained in these Terms
            and Conditions, windsor trade shall not be liable to you or any
            Customer for any special, indirect, incidental or consequential
            damages arising in connection with these Terms and Conditions or
            otherwise.{" "}
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            4.2 For any proven claims of any nature whatsoever, the total
            liability of windsor trade shall never exceed windsor trade Fees for
            a 7 (seven) day period immediately preceding from the date of the
            relevant claim or demand.
          </div>
        </div>
      </div>

      <div className="m-4 p-3 ">
        <div className="text-lg font-serif  ">5. NO WARRANTY</div>
        <div className="mr-6 ">
          <div className="text-sm mt-3 text-stone-700 text-justify">
            5.1.Except as expressly provided herein, windsor trade disclaims all
            warranties, responsibilities, express or implied, written or oral,
            including but not limited towards warranties of merchantability, any
            service interruptions (including on account of communication
            outages, system failures or other interruptions that may affect the
            receipt, processing, acceptance, completion or settlement of
            Transactions) and fitness of windsor trade Services and it does not
            warrant that the functions contained in windsor trade Services shall
            be uninterrupted or error free.{" "}
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            5.2. Use of windsor trade Services in no way represents any
            endorsement of you by windsor trade. windsor trade is not obligated
            to mediate disputes between Customers and Merchants or between a
            Customer and you or any payment system participants.
          </div>
        </div>
      </div>

      <div className="m-4 p-3 ">
        <div className="text-lg font-serif  ">6. MISCELLANEOUS</div>
        <div className="mr-6 ">
          <div className="text-sm mt-3 text-stone-700 text-justify">
            6.1. Cooperation.You acknowledge that your timely provision of
            access to your systems and various devices, as well as assistance,
            processes, cooperation, complete and accurate information and data
            from your officers, agents, and employees and suitably configured
            hardware and software are essential to performance of any windsor
            trade Services. You shall allow windsor trade to audit and inspect
            business processes followed by you related to windsor trade Services
            and suggest suitable changes thereto.
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            6.2. Commercial Communication. You acknowledge that you may receive
            communication over voice calls and messages regarding windsor trade
            Services, and products, and such other promotional communications.
            You unconditionally consent that such communications are:
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify p-4">
            <li>upon your request and authorization;</li>
            <li>
              not 'unsolicited commercial communications' as per the guidelines
              of Telecom Regulation Authority{" "}
            </li>
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            6.3. Independent contractors. Nothing in these Terms and Conditions
            shall be deemed to constitute either Party a partner, agent or legal
            representative of the other Party, or to create any fiduciary
            relationship between the Parties.
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            6.4. Severability. It is the intent of the Parties that in case any
            one or more of the provisions contained in these Terms and
            Conditions shall be held to be invalid or unenforceable in any
            respect, such provision shall be modified to the extent necessary to
            render it, as modified, valid and enforceable under applicable laws
            and such invalidity or unenforceability shall not affect other
            provisions of these Terms and Conditions.
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            6.5. Notices. Notices to be issued pursuant to these Terms and
            Conditions shall be delivered to the registered address of the
            relevant Party as first mentioned herein, or such other address as
            may be notified by the relevant Party (such change to address shall
            come into effect 5 (five) business days after delivery thereof).
          </div>
        </div>
      </div>

      <div className="m-4 p-3 ">
        <div className="text-2xl font-serif  ">ANNEXURE </div>
        <div className="text-lg font-serif  ">Prohibited Services</div>

        <div className="mr-6 ">
          <div className="text-sm mt-3 text-stone-700 text-justify">
            1.Adult goods and services which includes pornography and other
            sexually suggestive materials (including literature, imagery and
            other media); escort or prostitution services; Website access and/or
            website memberships of pornography or illegal sites;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            2.Alcohol which includes alcohol or alcoholic beverages such as
            beer, liquor, wine, or champagne;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            3.Body parts which includes organs or other body parts;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            4.Bulk marketing tools which includes email lists, software, or
            other products enabling unsolicited email messages (spam);
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            5.Cable descramblers and black boxes which includes devices intended
            to obtain cable and satellite signals for free;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            6.Child pornography which includes pornographic materials involving
            minors;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            7.Copyright unlocking devices which includes Mod chips or other
            devices designed to circumvent copyright protection;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            8.Copyrighted media which includes unauthorized copies of books,
            music, movies, and other licensed or protected materials;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            9.Copyrighted software which includes unauthorized copies of
            software, video games and other licensed or protected materials,
            including OEM or bundled software;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            10.Counterfeit and unauthorized goods which includes replicas or
            imitations of designer goods; items without a celebrity endorsement
            that would normally require such an association; fake autographs,
            counterfeit stamps, and other potentially unauthorized goods;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            11.Drugs and drug paraphernalia which includes illegal drugs and
            drug accessories, including herbal drugs like salvia and magic
            mushrooms;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            12.Drug test circumvention aids which includes drug cleansing
            shakes, urine test additives, and related items;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            13.Endangered species which includes plants, animals or other
            organisms (including product derivatives) in danger of extinction;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            14.Gaming/gambling which includes lottery tickets, sports bets,
            memberships/ enrolment in online gambling sites, and related
            content;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            15.Government IDs or documents which includes fake IDs, passports,
            diplomas, and noble titles;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            16.Hacking and cracking materials which includes manuals, how-to
            guides, information, or equipment enabling illegal access to
            software, servers, website, or other protected property;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            17.Illegal goods which includes materials, products, or information
            promoting illegal goods or enabling illegal acts;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            18.Miracle cures which includes unsubstantiated cures, remedies or
            other items marketed as quick health fixes;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            19.Offensive goods which includes literature, products or other
            materials that:
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify p-4">
            <li>
              Defame or slander any person or groups of people based on race,
              ethnicity, national origin, religion, sex, or other factors;
            </li>
            <li>Encourage or incite violent acts;</li>
            <li>Promote intolerance or hatred.</li>
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            20.Offensive goods, crime which includes crime scene photos or
            items, such as personal belongings, associated with criminals;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            21.Pyrotechnic devices, combustibles, corrosives and hazardous
            materials which includes explosives and related goods; toxic,
            flammable, and radioactive materials and substances;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            22.Regulated goods which includes air bags; batteries containing
            mercury; Freon or similar substances/refrigerants;
            chemical/industrial solvents; government uniforms; car titles;
            license plates; police badges and law enforcement equipment;
            lock-picking devices; pesticides; postage meters; recalled items;
            slot machines; surveillance equipment; goods regulated by government
            or other agency specifications;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            23.Securities which includes government bonds or related financial
            products;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            24.Tobacco and cigarettes which includes cigarettes, cigars, chewing
            tobacco, and related products;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            25.Traffic devices which includes radar detectors/jammers, license
            plate covers, traffic signal changers, and related products;
          </div>

          <div className="text-sm mt-3 text-stone-700 text-justify">
            26.Weapons which includes firearms, ammunition, knives, brass
            knuckles, gun parts, and other armaments;
          </div>

          <div className="text-sm mt-3 text-stone-700 text-justify">
            27.Wholesale currency which includes discounted currencies or
            currency exchanges;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            28.Live animals or hides/skins/teeth, nails and other parts etc. of
            animals;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            29.Live animals or hides/skins/teeth, nails and other parts etc. of
            animals;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            30.Multi-Level Marketing collection fees;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            31.Work-at-home approach and/or Work-at-home information;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            32.Any product or service which is not in compliance with all
            applicable laws and regulations whether federal, state, local or
            international, including the laws of India;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            33.Any product or service which is not in compliance with all
            applicable laws and regulations whether federal, state, local or
            international, including the laws of India;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            34.The Merchants providing services that have the potential of
            casting the Payment Gateway Facilitators in a poor light and/or that
            may be prone to Buy & Deny attitude of the cardholders when billed
            (e.g. Adult material/ Mature content/Escort services/ friend
            finders) and thus leading to chargeback and fraud losses;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            35.Businesses or website that operate within the scope of laws which
            are not absolutely clear or are ambiguous in nature (e.g. Web-based
            telephony, Website supplying medicines or controlled substances,
            website that promise online match-making);
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            36.Businesses out rightly banned by law (e.g. Betting & Gambling/
            publications or content that is likely to be interpreted by the
            authorities as leading to moral turpitude or decadence or incite
            caste/communal tensions, lotteries/sweepstakes & games of chance;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            37.The Merchants who deal in intangible goods/ services (eg.
            Software download/ Health/ Beauty Products), and businesses involved
            in pyramid marketing schemes or get-rich-quick schemes. Any other
            product or Service, which in the sole opinion of windsor trade, is
            detrimental to the image and interests of windsor trade, as
            communicated by either of them/ both of them to the Merchant from
            time to time. This shall be without prejudice to any other terms &
            conditions mentioned in these Terms and Conditions;
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            38.Bulk marketing tools which includes email, lists, software, or
            other products enabling unsolicited email messages (spam);
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            39.Web-based telephony/ SMS/Text/Facsimile services or Calling
            Cards. Bandwidth or Data transfer/ allied services. Voice process
            /knowledge process services; and
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            40.Mailing lists
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            41.Virtual currency or credits that can be monetized, re-sold or
            converted to physical or digital goods or services or otherwise exit
            the virtual world.
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            42.Money laundering services.
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            43.Database providers (for tele-callers).
          </div>
          <div className="text-sm mt-3 text-stone-700 text-justify">
            44.Firms promoting business opportunities, investment opportunities
            and mortgages
          </div>
        </div>
      </div>
    </div>
  )
}

export default TermsPage1
